# Generated by Django 3.2.6 on 2021-09-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('is_on_sale', models.BooleanField(default=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('normal_price', models.FloatField(blank=True, null=True)),
                ('savings', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating_text', models.CharField(blank=True, max_length=20, null=True)),
                ('rating_percent', models.IntegerField(blank=True, null=True)),
                ('rating_count', models.BigIntegerField(blank=True, null=True)),
                ('release_date', models.BigIntegerField(blank=True, null=True)),
                ('last_change', models.BigIntegerField(blank=True, null=True)),
                ('deal_rating', models.FloatField(blank=True, null=True)),
                ('img_url', models.URLField(blank=True, max_length=120, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.store')),
            ],
        ),
    ]
