# Generated by Django 3.2.6 on 2021-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='internal_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
