# Generated by Django 3.2.6 on 2021-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_store_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='header_img',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='internal_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
