# Generated by Django 3.2.6 on 2021-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20210904_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='header_img',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='img_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rating_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
